In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [7]:
diabet = pd.read_csv('diabetes.csv')

In [8]:
diabet

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [9]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [10]:
diabet = diabet.sample(frac = 1)

In [11]:
diabet

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
587            6      103             66              0        0  24.3   
93             4      134             72              0        0  23.8   
260            3      191             68             15      130  30.9   
478            8      126             74             38       75  25.9   
651            1      117             60             23      106  33.8   
..           ...      ...            ...            ...      ...   ...   
743            9      140             94              0        0  32.7   
15             7      100              0              0        0  30.0   
453            2      119              0              0        0  19.6   
51             1      101             50             15       36  24.2   
284            2      108             80              0        0  27.0   

     DiabetesPedigreeFunction  Age  Outcome  
587                     0.249   29        0  
93                      0.277   60        1  
260                     0.299   34        0  
478                     0.162   39        0  
651                     0.466   27        0  
..                        ...  ...      ...  
743                     0.734   45        1  
15                      0.484   32        1  
453                     0.832   72        0  
51                      0.526   26        0  
284                     0.259   52        1  

[768 rows x 9 columns]

In [15]:
A = diabet.drop(['Outcome'], axis = 1).values
b = diabet ['Outcome'].values

In [16]:
A

array([[  6.   , 103.   ,  66.   , ...,  24.3  ,   0.249,  29.   ],
       [  4.   , 134.   ,  72.   , ...,  23.8  ,   0.277,  60.   ],
       [  3.   , 191.   ,  68.   , ...,  30.9  ,   0.299,  34.   ],
       ...,
       [  2.   , 119.   ,   0.   , ...,  19.6  ,   0.832,  72.   ],
       [  1.   , 101.   ,  50.   , ...,  24.2  ,   0.526,  26.   ],
       [  2.   , 108.   ,  80.   , ...,  27.   ,   0.259,  52.   ]])

In [17]:
b

array([0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,

In [18]:
A_train, A_test, b_train, b_test = train_test_split(A, b, random_state = 36)

In [19]:
knn = KNeighborsClassifier()

In [20]:
knn.fit(A_train, b_train)

KNeighborsClassifier()

In [21]:
b_pred = knn.predict(A_test)

In [22]:
b_pred

array([0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0], dtype=int64)

In [24]:
accuracy_score(b_pred, b_test)

0.71875

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
std = StandardScaler()
A_train_scaled = std.fit_transform(A_train)

In [27]:
A_test_scaled = std.transform(A_test)

In [28]:
knn.fit(A_train_scaled, b_train)

KNeighborsClassifier()

In [29]:
b_pred = knn.predict(A_test_scaled)

In [31]:
accuracy_score(b_test, b_pred)

0.6979166666666666